2022.02.19 TIL

## ✏️ 에러 처리 1
에러 처리에는 다음 세 과정이 필요하다.
1. 오류의 종류 정의하기
2. 발생한 오류 던지기(throw)
3. 던진 오류 처리하기

1. 오류의 종류 정의하기
```swift
enum ErrorCode : Error {
    case outOfRange
    case soldOut
    case outOfBudget
}
```
오류 정의는 enum 타입으로 정의한다.
특정 케이스 별로 오류처리하지 않을 때는 이 과정을 거치지 않아도 됨.

2. 발생한 오류 던지기(throw)
```swift
func buySomeProduct(productName: Int) throws {  // 함수 파라미터와 반환 타입 사이에 throws 삽입
    ...
    guard let product = productList[productNumber] else {
        throw ErrorCode.soldOut // soldOut 에러를 던진다.
    }
}
```

에러가 발생할 수 있는 구간에 throw 에러 타입을 써준다. 
else 내부에 처리 로직을 넣을 수 있지만, 에러 처리를 위해 일단 에러를 던지게 함


3. 던진 오류 처리하기
```swift
do {
    try buySomeProduct(productNumber: 9999)
} catch ErrorCode.outOfRange {
    ...
} catch ErrorCode.soldOut {
    ...
} catch ErrorCode.outOfBudget {
    ...
} catch {
    // 처리되지 않은 나머지 에러
}
```

코드 실행은 ```do - try - catch```문으로 실행한다. 각 부분의 의미는 다음과 같다.
* do: '아래의 코드를 실행하겠습니다.'
* try: '에러 발생할 수도 있는데 한 번 시도해볼게요. 에러 발생하면 잡아주세요.'
* catch: '에러가 발생하면 이놈이 어떤 에러인지 찾아서 이렇게 처리하겠습니다.'

## ✏️ 에러 처리 2
함수 호출때마다 케이스를 나눠줘야 한다면 코드의 길이가 불필요하게 길어진다 >> ```Error```를 ```LocalizedError```로 확장(extension)
* LocalizedError: 에러 및 에러 발생 원인을 설명하는 지역화된 메시지를 제공하는 특수 에러 프로토콜
```swift
extension ErrorCode: LocalizedError {
    var errorDescription: String? {
        switch self {
        case .outOfRange:
            return "존재하지 않는 상품번호입니다."
        case .soldOut:
            return "품절된 상품번호입니다."
        case .outOfBudget:
            return "예산을 초과하여 구매할 수 없습니다."
        }
    }
}
```

코드 실행
```swift
do {
    try buySomeProduct(productNumber: 9999)
} catch let error as ErrorCode {
    print(error.errorDescription ?? "처리되지 않은 예외사항 \(error)입니다.")
} 
```

## ✏️ 프로토콜 확장
이전에 ```CaseIterable```을 쓰면서
```swift
enum Card: String, CaseIterable { ... }
```
이렇게 쓴 적이 있었는데, 이렇게 상속받는 것과 extension으로 확장하는 것은 의미 상 동일하다고 한다.
그러나 코드의 가독성 향상을 위해 확장과 관련된 내용은 extension 키워드와 함께 묶어주는 것이 좋다고 한다!
